---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  instancio:
    bean:
      validation:
        enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0

