spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:file:./my.db
    username: sa
    password: pass
  #  development:
  #    username: admin
  #    password: testdb
  #    url: jdbc:postgresql://localhost:5432/testdb?user=admin&password=testdb